# Generated by Django 5.2.7 on 2025-10-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountprofile',
            options={'verbose_name': 'ملف مستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم الكامل'),
        ),
    ]
