# Generated by Django 5.2.7 on 2025-10-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'استشارة', 'verbose_name_plural': 'الاستشارات'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consultations_images/', verbose_name='صورة الاستشارة'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='تاريخ ووقت الموعد'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الاستشارة'),
        ),
    ]
