# Generated by Django 5.2.7 on 2025-10-06 20:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_consultation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الاستشارة'),
        ),
    ]
