# Generated by Django 5.2.7 on 2025-10-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='scheduled_date',
        ),
    ]
