# Generated by Django 5.2.7 on 2025-10-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'verbose_name': 'خطة دفع', 'verbose_name_plural': 'خطط الدفع'},
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_name',
            field=models.CharField(max_length=100, verbose_name='اسم الخطة'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
    ]
